### PR TITLE
Fix display current day in calendar

### LINKED ISSUE #1298: Display current day in calendar
Most calendars makes it obvious what day it is by glancing at the calendar. Some also fades out the days that have passed.

screenshot 2018-10-10 08 35 25

### PR DESCRIPTION
**Pull request by amalieeh**
Fix #1298 by view current day and enlighten upcoming events.

Before:
image

After:
image

### CODE REVIEW

File: app/components/Search/SearchPage.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ type Props = {
   onQueryChanged: string => void,
   placeholder?: string,
   results: Array<SearchResult>,
-  handleSelect: SearchResult => void
+  handleSelect: SearchResult => Promise<*>
```
Comment (SmithPeder) [inline app/components/Search/SearchPage.js]: Hehe, you fixed this in:
https://github.com/webkom/lego-webapp/pull/1270/files
, and will get a merge conflict if either of these pull requests go through.

**Comment by odinuge** [comment]
Smoooooth! :sunglasses:
