### PR TITLE
Fix count on abacard and attendees

### LINKED ISSUE #1224: Abacard attendance count includes waiting list
skjermbilde 2018-04-24 kl 14 17 11
skjermbilde 2018-04-24 kl 14 17 05

Gotta change `{registerCount}/{registered.length} har møtt opp` into `{registerCount}/{totalCapacity} har møtt opp` or something like that, depending on what data you have available. Both in Abacard and Event Administrate.

### PR DESCRIPTION
**Pull request by amalieeh**
Fix #1224 by not include waitinglist in count on Abacard and attendees.

### CODE REVIEW

File: app/routes/events/components/EventAdministrate/Abacard.js [hunk 1]
```diff
@@ -25,7 +37,7 @@ class Abacard extends React.Component<*, State> {
     setTimeout(() => this.setState({ showCompleted: false }), 2000);
   };
 
-  handleSelect = (result: SearchResult) => {
+  handleSelect = (result: any) => {
```
Comment (SmithPeder) [inline app/routes/events/components/EventAdministrate/Abacard.js]: Why could this not be of type `SearchResult`, if results in an array of `SearchResults`?
